name: Build Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  OUTPUT_FOLDER: "./output"
  
jobs:
  pack-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for deployment
        uses: actions/checkout@v5

      - name: Prepare library package
        run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/utils/crc
          cp ./crc16.c ./${{ env.OUTPUT_FOLDER }}/utils/crc/
          cp ./crc16.h ./${{ env.OUTPUT_FOLDER }}/utils/crc/
 
      - name: Pack files for upload
        run: |
          tar -czvf build.tar.gz ${{ env.OUTPUT_FOLDER }}
          zip -r build.zip ${{ env.OUTPUT_FOLDER }}

      - name: Upload library package
        uses: actions/upload-artifact@v4
        with:
            name: library-package
            path: ${{ env.OUTPUT_FOLDER }}
            retention-days: 1